In [97]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

from sklearn.impute import SimpleImputer
from sklearn.pipeline import Pipeline
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score, classification_report

import seaborn as sns
from sklearn.svm import SVC
from sklearn.metrics import classification_report, confusion_matrix
from sklearn.preprocessing import LabelEncoder



In [98]:
#Run SVM algorithm on that data
gym_df = pd.read_csv('gym.csv')
gym_df.dropna

label_encoder = LabelEncoder()
gym_df['Gender_Encoded'] = label_encoder.fit_transform(gym_df['Gender'])
gym_df['Workout_Type_Encoded'] = label_encoder.fit_transform(gym_df['Workout_Type'])

gym_df.head()
x = gym_df.iloc[:, [0, 2, 3, 4, 5, 6, 7, 8,10,11,12,14]]
y = gym_df.iloc[:, [13, 16, 15]]
x
y


Experience_Level  Workout_Type_Encoded  Gender_Encoded
0                   3                     3               1
1                   2                     1               0
2                   2                     0               0
3                   1                     2               1
4                   1                     2               1
..                ...                   ...             ...
968                 3                     2               1
969                 1                     2               1
970                 3                     0               0
971                 2                     1               1
972                 1                     2               1

[973 rows x 3 columns]

In [99]:
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size=0.4, random_state=42)

# Standardize the features
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

# Train the SVM model with RBF kernel
svm_model = SVC(kernel='rbf', random_state=42)
svm_model.fit(X_train_scaled, y_train['Experience_Level'])  # Example: Using Experience_Level as target

# Make predictions
y_pred = svm_model.predict(X_test_scaled)

# Evaluate the model
accuracy = accuracy_score(y_test['Experience_Level'], y_pred)
print(f"Accuracy: {accuracy * 100:.2f}%")

# Detailed classification report
print(classification_report(y_test['Experience_Level'], y_pred))

Accuracy: 89.23%
              precision    recall  f1-score   support

           1       0.92      0.80      0.85       153
           2       0.82      0.93      0.87       157
           3       1.00      1.00      1.00        80

    accuracy                           0.89       390
   macro avg       0.91      0.91      0.91       390
weighted avg       0.90      0.89      0.89       390



In [100]:
knn_model = KNeighborsClassifier(n_neighbors=5)  # You can tune the number of neighbors
knn_model.fit(X_train_scaled, y_train['Experience_Level'])

# Make predictions
y_pred = knn_model.predict(X_test_scaled)

# Evaluate the model
accuracy = accuracy_score(y_test['Experience_Level'], y_pred)
print(f"Accuracy: {accuracy * 100:.2f}%")

# Detailed classification report
print(classification_report(y_test['Experience_Level'], y_pred))

Accuracy: 85.13%
              precision    recall  f1-score   support

           1       0.85      0.75      0.80       153
           2       0.78      0.87      0.83       157
           3       1.00      1.00      1.00        80

    accuracy                           0.85       390
   macro avg       0.88      0.87      0.87       390
weighted avg       0.85      0.85      0.85       390



In [101]:
x_train, x_test, y_train, y_test= train_test_split(x, y, test_size = 0.2, shuffle = True, random_state = 0)

In [102]:
# Train models with and without standard scaler
scaler = StandardScaler()
scaler.fit(x_train)

x_train_scaled = scaler.transform(x_train)
x_test_scaled = scaler.transform(x_test)

In [103]:
# Step 1: Scale the features
x_scaled = scaler.transform(x)

# Step 2: Create a DataFrame from the scaled features, preserving the column names
gym_df_scaled = pd.DataFrame(x_scaled, columns=x.columns)

# Step 3: Add the target columns from y to the scaled DataFrame
# Iterate through each column of y (assuming y is a DataFrame)
for col in y.columns:  # Use y.columns to get target column names
    gym_df_scaled[col] = y[col]

# Step 4: Verify the result
print(gym_df_scaled.head())  # Display the first few rows of the updated DataFrame


        Age  Weight (kg)  Height (m)   Max_BPM   Avg_BPM  Resting_BPM  \
0  1.429708     0.704658   -0.103686  0.022980  0.925993    -0.325290   
1  0.609902     0.065591   -1.507964 -0.063810  0.506492     0.487587   
2 -0.537827    -0.258711   -0.493764 -1.105291 -1.521095    -1.138168   
3 -1.111691    -0.969316   -0.181702  0.890881  1.415411    -0.867209   
4 -0.045943    -1.307926    0.520437  0.717301  0.995910     0.758547   

   Session_Duration (hours)  Calories_Burned  Fat_Percentage  \
0                  1.257119         1.481737       -1.988557   
1                  0.117452        -0.092000        1.405563   
2                 -0.437770        -0.845929        1.325889   
3                 -1.957326        -1.376608        0.592886   
4                 -1.811215        -1.288772        0.656626   

   Water_Intake (liters)  Workout_Frequency (days/week)       BMI  \
0               1.439005                       0.739667  0.816372   
1              -0.873083              

In [104]:
# Step 1: Combine the original features with the target columns
gym_df_combined = x.copy()  # Retain original features
for col in y.columns:       # Append target columns
    gym_df_combined[col] = y[col]

# Step 2: Verify the result
print(gym_df_combined.head())  # Display the first few rows of the updated DataFrame

   Age  Weight (kg)  Height (m)  Max_BPM  Avg_BPM  Resting_BPM  \
0   56         88.3        1.71      180      157           60   
1   46         74.9        1.53      179      151           66   
2   32         68.1        1.66      167      122           54   
3   25         53.2        1.70      190      164           56   
4   38         46.1        1.79      188      158           68   

   Session_Duration (hours)  Calories_Burned  Fat_Percentage  \
0                      1.69           1313.0            12.6   
1                      1.30            883.0            33.9   
2                      1.11            677.0            33.4   
3                      0.59            532.0            28.8   
4                      0.64            556.0            29.2   

   Water_Intake (liters)  Workout_Frequency (days/week)    BMI  \
0                    3.5                              4  30.20   
1                    2.1                              4  32.00   
2                   

In [105]:
y_train = y_train.values.ravel()  # y_train on pandas DataFrame

In [106]:
# Skaalaus vain jaon jälkeen
scaler = StandardScaler()
x_train_scaled = scaler.fit_transform(x_train)
x_test_scaled = scaler.transform(x_test)

# Vahvista rivimäärät
print(f"x_train_scaled shape: {x_train_scaled.shape}")
print(f"y_train shape: {y_train.shape}")

x_train_scaled shape: (778, 12)
y_train shape: (2334,)


In [107]:
x_train_scaled, x_test_scaled, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)

In [108]:
y_train = y_train.iloc[:, 0]  # Valitaan "Experience_Level" (ensimmäinen sarake)
print(y_train.shape)  # Tämä pitäisi olla (778,)

(778,)


In [109]:
model = SVC(kernel="linear")
model.fit(x_train_scaled, y_train)

# Ennustetaan koko testijoukko
y_pred = model.predict(x_test_scaled)
print(y_pred.shape)  

(195,)


In [110]:
# y_test on DataFrame ja valitaan ensimmäinen sarake
if len(y_test.shape) > 1:
    y_test = y_test.iloc[:, 0]  # Valitaan "Experience_Level" (ensimmäinen sarake)

# Tarkista y_test ja y_pred muodot
print("y_test shape after fix:", y_test.shape)
print("y_pred shape:", y_pred.shape)

# Jos y_pred on 2D, valitse ensimmäinen sarake
if len(y_pred.shape) > 1:
    y_pred = y_pred[:, 0]  # Otetaan ensimmäinen sarake, jos y_pred on 2D

# Confusion matrix
cm = confusion_matrix(y_test, y_pred)
print("Confusion Matrix:")
print(cm)

y_test shape after fix: (195,)
y_pred shape: (195,)
Confusion Matrix:
[[66 12  0]
 [ 8 67  0]
 [ 0  0 42]]


List 2 interesting use cases for applying SVM algorithm for real world

In [111]:
#Compare SVM results with kNN results